# Generated by Django 3.0.7 on 2020-07-08 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Man',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fio', models.CharField(db_index=True, max_length=50)),
                ('Card', models.CharField(db_index=True, max_length=50)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fio', models.CharField(db_index=True, max_length=80)),
                ('survey', models.CharField(db_index=True, max_length=80)),
                ('Card', models.CharField(db_index=True, max_length=80)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Status_Record',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Stat', models.CharField(db_index=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Surveys',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Survey', models.CharField(db_index=True, max_length=50)),
            ],
        ),
    ]
