# Generated by Django 3.0.8 on 2020-07-30 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='status',
            field=models.CharField(db_index=True, default='Ожидает', max_length=40),
        ),
    ]
