# Generated by Django 3.0.8 on 2020-07-31 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0002_record_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveys',
            name='Survey',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='surveys',
            name='id',
            field=models.IntegerField(db_index=True, primary_key=True, serialize=False),
        ),
    ]
